### ISSUE TITLE
Merge Word Documents

### ISSUE THREAD

**Issue by vonyang** [python-openxml/python-docx#1244] opened 2023-09-19 09:53 UTC
I have 3 files: ['doc1.docx', 'doc2.docx', 'doc3.docx']
I want to merged all of them in a single file, I found some functions to do it like this, using "docxcomposer" library, that merged with styles but it doesn't work well:
```
def combine_all_docx(filename_master,files_list):
    number_of_sections=len(files_list)
    master = Document_compose(filename_master)
    composer = Composer(master)
    for i in range(0, number_of_sections):
        doc_temp = Document_compose(files_list[i])
        composer.append(doc_temp)
    composer.save("combined_file.docx")
```
or this, that doesn't copy the images neither some styles:
```
doc1 = docx.Document('1.docx')
doc2 = docx.Document('2.docx')
for element in doc2.element.body:
    doc1 .element.body.append(element)
doc1.save('new.docx')
```
I want to copy all the content of the docx file to insert into the first file or a new file.

**Comment by scanny** [comment] 2023-09-24 00:23
Duplicate of #44.

**Closed by scanny** 2023-09-24 00:23 UTC
