### ISSUE TITLE
docs: update property movement to ParagraphFormat

### ISSUE THREAD

**Issue by waterdr0p** [python-openxml/python-docx#296] opened 2016-05-27 01:39 UTC
https://python-docx.readthedocs.io/en/latest/user/text.html
The following code is valid （replace ）
# Indentation

p2 = document.add_paragraph('left_indent ' \* 25)
p2_format = p2.paragraph_format
p2_format.left_indent = Inches(0.5) # **p2.left_indent will be invalid**
print('p2_format = {}'.format(p2_format.left_indent))
print('p2_format.inches = {}'.format(p2_format.left_indent.inches))
## right_indent

p3 = document.add_paragraph('right_indent ' \* 25)
p3_format = p3.paragraph_format
p3_format.right_indent = Pt(24)
print('p3_fmt.right_indent_indent = {}'.format(p3_format.right_indent))
print('p3_fmt.right_indent_indent.pt = {}'.format(p3_format.right_indent.pt))
## first_line_indent

p4 = document.add_paragraph('first_line_indent'*26)
p4_format = p4.paragraph_format
p4_format.first_line_indent = Inches(1)
print('p4_format.first_line_indent.inches = {}\
        '.format(p4_format.first_line_indent.inches))

The code from official v0.8.5 will be failure

> > > from docx.shared import Inches
> > > paragraph = document.add_paragraph()
> > > paragraph_format = paragraph.paragraph_format
> > > 
> > > paragraph.left_indent
> > > None  # indicating indentation is inherited from the style hierarchy
> > > paragraph.left_indent = Inches(0.5)
> > > paragraph.left_indent
> > > 457200
> > > paragraph.left_indent.inches
> > > 0.5

**Comment by scanny** [comment] 2016-05-27 06:35
What is the error message you are receiving and what code will reproduce it?

**Comment by waterdr0p** [comment] 2016-05-27 06:45
There is no error message, but docx document will show nothing changing by the "Error Code"
for example:
p3 = document.add_paragraph('right_indent ' * 25)
p3_format = p3.paragraph_format
p3_format.right_indent = Pt(24) # docx will indent OK!
p3.right_indent = Pt(24) # there is no change for identation in docx
Env: python3.5.1, windows

**Comment by scanny** [comment] 2016-05-27 17:39
Ah, ok, now I see what you're getting at.

The reason is that left_indent (and right_indent, and several others) moved into ParagraphFormat.

So when you make an assignment, a new attribute (e.g. 'right_indent' in your example) is added to the Paragraph object, but doesn't do anything other than store the value you assign.

I'll update the documentation. Thanks for the heads up :)

**Comment by scanny** [comment] 2016-05-27 17:41
Note to self: also check into making Paragraph inherit from ParentedElementProxy so attempts to assign to non-existent attributes raises an exception.

**Comment by scanny** [comment] 2016-05-27 21:06
Fixed. Will appear in next release.

**Comment by scanny** [comment] 2018-08-18 21:03
Fixed in release v0.8.7 circa Aug 18 2018.

**Closed by scanny** 2018-08-18 21:03 UTC
Labels: documentation, shortlist
