### ISSUE TITLE
Feature: add_table() before and after parameter

### ISSUE THREAD

**Issue by xdml** [python-openxml/python-docx#794] opened 2020-03-13 09:41 UTC
This is similar to #793 but for tables.

I suggest to define table creation as follows:

```python
def add_table(self, rows, cols, style=None, before=None, after=None):
```

where both `before` and `after` parameters will accept `Paragraph` instance of paragraph the table is inserting, `before` in case table is inserting before the paragraph in `before`, and similarly for `after`.

If both `before` and `after` parameters are provided, some exception should be raised.

**Comment by scanny** [comment] 2020-04-05 23:08
Duplicate of #478

**Closed by scanny** 2020-04-05 23:08 UTC
