### ISSUE TITLE
Multiple text columns

### ISSUE THREAD

**Issue by HereComesEverybody** [python-openxml/python-docx#308] opened 2016-07-06 15:45 UTC
How can I change the layout after a specific point so that the text flows in two columns rather than one?

**Comment by scanny** [comment] 2016-07-06 20:01
Closing this as duplicate of #167.

The short story is it isn't implemented yet. If you want to go down to the lxml level, you can get close with Section._sectPr. Columns are controlled with the `w:cols` element (CT_Columns) underneath the `w:sectPr` element.

**Closed by scanny** 2016-07-06 20:01 UTC
