### ISSUE TITLE
Wrong info and result in Quickstart - https://python-docx.readthedocs.io/en/latest/user/quickstart.html

### ISSUE THREAD

**Issue by AlkisPis** [python-openxml/python-docx#994] opened 2021-08-25 06:33 UTC
Re: Quickstart - https://python-docx.readthedocs.io/en/latest/user/quickstart.html

The document says, _By default, the added image appears at native size._  This is not what is happening:
Adding an image with `document.add_picture('image-filename.png')` creates an image magnified by **65%**!!!

**Comment by scanny** [comment] 2021-08-25 16:18
duplicate of #995. @AlkisPis if you're serious about getting solutions then please provide the required information in your issue posts, like in this case why you say it appears magnified, what the "native size" is and how you know that. If you are unwilling to do that then please refrain from posting issues. We cannot help you if you don't do the work required to provide us basis for diagnosis.

**Closed by scanny** 2021-08-25 16:18 UTC
