### ISSUE TITLE
There is any way to insert SVG picture into word document ?

### ISSUE THREAD

**Issue by Mkamal88** [python-openxml/python-docx#659] opened 2019-04-09 22:25 UTC
I'm trying to insert svg into word document but I got this error:
docx.image.exceptions.UnrecognizedImageError

it seems the function add_picture doesn't support svg format, but it can be done using word UI

**Comment by madphysicist** [comment] 2019-04-12 00:46
Seems like duplicate of #651.

**Comment by scanny** [comment] 2019-04-12 03:47
I agree. Closing as duplicate of #651. Thanks @madphysicist :)

**Closed by scanny** 2019-04-12 03:47 UTC

**Comment by goomesthiago** [comment] 2024-04-24 12:52
Is there any update on this? Does python-docx already supports adding svg images into a word document?
