### ISSUE TITLE
How to set height of cell

### ISSUE THREAD

**Issue by hervekhg** [python-openxml/python-docx#152] opened 2015-02-24 08:43 UTC
Hi,
I want to set a minimun height of cell of my table but I don't know how could i do it.
Could you help me please ?

**Comment by scanny** [comment] 2015-02-25 00:50
Duplicate of #96.

@hervekhg if that doesn't answer your question you can post another comment on that issue and I'll respond to it there.

**Closed by scanny** 2015-02-25 00:50 UTC
